ARCHS = arm64 arm64e
GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

TOOL_NAME = ForwardNotifierReceiver

ForwardNotifierReceiver_FILES = main.m
ForwardNotifierReceiver_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tool.mk
